/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tbordovsky.teapot;

import org.junit.Test;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

public class AppTest {
    @Test
    public void testMatchCorrectHttpVersion() {
        Pattern httpPattern = App.TeapotHandler.HTTP_PATTERN;

        Matcher matcher = httpPattern.matcher("GET www.google.com HTTP/1.1");
        assertTrue(matcher.matches());
        assertEquals("1.1", matcher.group(1));
    }
}
